export { CarritoPage } from "./carrito/carrito.page";
export { CategoriasPage } from "./categorias/categorias.page";
export { HomePage } from "./home/home.page";
export { LoginPage } from "./login/login.page";
export { OrdenesPage } from "./ordenes/ordenes.page";
export { OrdenesDetallePage } from "./ordenes-detalle/ordenes-detalle.page";
export { PorCategoriasPage } from "./por-categorias/por-categorias.page";
export { ProductoPage } from "./producto/producto.page";
export { TabsPage } from "./tabs/tabs.page";